### PR TITLE
Update boost and add boost/locale.hpp

### PR DESCRIPTION
**Pull request by LNDF**
For more information on why this is needed, see https://github.com/shadps4-emu/shadPS4/pull/1267

### CODE REVIEW

**Comment by polybiusproxy** [comment]
Hi, I'd appreciate if you could add these:
- boost/align/aligned_alloc.hpp
- boost/align/aligned_delete.hpp
- boost fibers

**Comment by LNDF** [comment]
boost/align/aligned_alloc.hpp was already there. I added boost/align/aligned_delete.hpp and boost/fibers/all.hpp.

**Comment by raphaelthegreat** [comment]
Was this generated with bcp with our trimmed header list? It adds 200k new lines which seems a lot to me just for locale

**Comment by LNDF** [comment]
> Was this generated with bcp with our trimmed header list? It adds 200k new lines which seems a lot to me just for locale

Yes. This was done using BCP and build.cmd before the "fix build.cmd" commit.

**Comment by LNDF** [comment]
Closing since this is not needed anymore.

**Pull request closed without merging**
